SUPABASE_HOST = "db.xmhmwtbnbdmrcvyvflrh.supabase.co"
SUPABASE_PORT = "5432"
SUPABASE_DBNAME = "postgres"
SUPABASE_USER = "postgres"
SUPABASE_PASSWORD = "sb_publishable_SNUuzHT9hwde1LgcQ7TJ9Q_ZK5wRMOr"